name: Pylint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint anybadge
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files 'puggle/*.py') --exit-zero
      - name: Create badge
        run: |
          anybadge -l pylint -v 2.22 -f puggle-pylint-badge.svg 2=red 4=orange 8=yellow 10=green
      - name: Push badge to badges repo
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_files: "puggle-pylint-badge.svg"
          destination-username: "michael-stewart-webdev"
          destination-repository: "nlp-tlp/badges"
          commit-email: "michael-stewart-webdev@gmail.com"
